// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.ui.recycler.DialogRecyclerView;

public final class DialogTabsBinding implements ViewBinding {
  @NonNull
  private final DialogRecyclerView rootView;

  @NonNull
  public final DialogRecyclerView tabRecycler;

  private DialogTabsBinding(@NonNull DialogRecyclerView rootView,
      @NonNull DialogRecyclerView tabRecycler) {
    this.rootView = rootView;
    this.tabRecycler = tabRecycler;
  }

  @Override
  @NonNull
  public DialogRecyclerView getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogTabsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogTabsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_tabs, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogTabsBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    DialogRecyclerView tabRecycler = (DialogRecyclerView) rootView;

    return new DialogTabsBinding((DialogRecyclerView) rootView, tabRecycler);
  }
}
