// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.ui.recycler.DialogRecyclerView;

public final class DialogAccentBinding implements ViewBinding {
  @NonNull
  private final DialogRecyclerView rootView;

  @NonNull
  public final DialogRecyclerView accentRecycler;

  private DialogAccentBinding(@NonNull DialogRecyclerView rootView,
      @NonNull DialogRecyclerView accentRecycler) {
    this.rootView = rootView;
    this.accentRecycler = accentRecycler;
  }

  @Override
  @NonNull
  public DialogRecyclerView getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogAccentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogAccentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_accent, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogAccentBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    DialogRecyclerView accentRecycler = (DialogRecyclerView) rootView;

    return new DialogAccentBinding((DialogRecyclerView) rootView, accentRecycler);
  }
}
