// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButtonToggleGroup;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;

public final class DialogMusicDirsBinding implements ViewBinding {
  @NonNull
  private final NestedScrollView rootView;

  @NonNull
  public final TextView dirsEmpty;

  @NonNull
  public final TextView dirsModeDesc;

  @NonNull
  public final Button dirsModeExclude;

  @NonNull
  public final Button dirsModeInclude;

  @NonNull
  public final RecyclerView dirsRecycler;

  @NonNull
  public final MaterialButtonToggleGroup folderModeGroup;

  private DialogMusicDirsBinding(@NonNull NestedScrollView rootView, @NonNull TextView dirsEmpty,
      @NonNull TextView dirsModeDesc, @NonNull Button dirsModeExclude,
      @NonNull Button dirsModeInclude, @NonNull RecyclerView dirsRecycler,
      @NonNull MaterialButtonToggleGroup folderModeGroup) {
    this.rootView = rootView;
    this.dirsEmpty = dirsEmpty;
    this.dirsModeDesc = dirsModeDesc;
    this.dirsModeExclude = dirsModeExclude;
    this.dirsModeInclude = dirsModeInclude;
    this.dirsRecycler = dirsRecycler;
    this.folderModeGroup = folderModeGroup;
  }

  @Override
  @NonNull
  public NestedScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogMusicDirsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogMusicDirsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_music_dirs, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogMusicDirsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.dirs_empty;
      TextView dirsEmpty = ViewBindings.findChildViewById(rootView, id);
      if (dirsEmpty == null) {
        break missingId;
      }

      id = R.id.dirs_mode_desc;
      TextView dirsModeDesc = ViewBindings.findChildViewById(rootView, id);
      if (dirsModeDesc == null) {
        break missingId;
      }

      id = R.id.dirs_mode_exclude;
      Button dirsModeExclude = ViewBindings.findChildViewById(rootView, id);
      if (dirsModeExclude == null) {
        break missingId;
      }

      id = R.id.dirs_mode_include;
      Button dirsModeInclude = ViewBindings.findChildViewById(rootView, id);
      if (dirsModeInclude == null) {
        break missingId;
      }

      id = R.id.dirs_recycler;
      RecyclerView dirsRecycler = ViewBindings.findChildViewById(rootView, id);
      if (dirsRecycler == null) {
        break missingId;
      }

      id = R.id.folder_mode_group;
      MaterialButtonToggleGroup folderModeGroup = ViewBindings.findChildViewById(rootView, id);
      if (folderModeGroup == null) {
        break missingId;
      }

      return new DialogMusicDirsBinding((NestedScrollView) rootView, dirsEmpty, dirsModeDesc,
          dirsModeExclude, dirsModeInclude, dirsRecycler, folderModeGroup);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
