// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.textfield.TextInputEditText;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.ui.coordinator.EdgeCoordinatorLayout;
import org.oxycblt.auxio.ui.recycler.EdgeRecyclerView;

public final class FragmentSearchBinding implements ViewBinding {
  @NonNull
  private final EdgeCoordinatorLayout rootView;

  @NonNull
  public final TextInputEditText searchEditText;

  @NonNull
  public final EdgeRecyclerView searchRecycler;

  @NonNull
  public final MaterialToolbar searchToolbar;

  private FragmentSearchBinding(@NonNull EdgeCoordinatorLayout rootView,
      @NonNull TextInputEditText searchEditText, @NonNull EdgeRecyclerView searchRecycler,
      @NonNull MaterialToolbar searchToolbar) {
    this.rootView = rootView;
    this.searchEditText = searchEditText;
    this.searchRecycler = searchRecycler;
    this.searchToolbar = searchToolbar;
  }

  @Override
  @NonNull
  public EdgeCoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentSearchBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentSearchBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_search, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentSearchBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.search_edit_text;
      TextInputEditText searchEditText = ViewBindings.findChildViewById(rootView, id);
      if (searchEditText == null) {
        break missingId;
      }

      id = R.id.search_recycler;
      EdgeRecyclerView searchRecycler = ViewBindings.findChildViewById(rootView, id);
      if (searchRecycler == null) {
        break missingId;
      }

      id = R.id.search_toolbar;
      MaterialToolbar searchToolbar = ViewBindings.findChildViewById(rootView, id);
      if (searchToolbar == null) {
        break missingId;
      }

      return new FragmentSearchBinding((EdgeCoordinatorLayout) rootView, searchEditText,
          searchRecycler, searchToolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
