// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.MaterialToolbar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.ui.coordinator.EdgeCoordinatorLayout;
import org.oxycblt.auxio.ui.recycler.EdgeRecyclerView;

public final class FragmentQueueBinding implements ViewBinding {
  @NonNull
  private final EdgeCoordinatorLayout rootView;

  @NonNull
  public final EdgeRecyclerView queueRecycler;

  @NonNull
  public final MaterialToolbar queueToolbar;

  private FragmentQueueBinding(@NonNull EdgeCoordinatorLayout rootView,
      @NonNull EdgeRecyclerView queueRecycler, @NonNull MaterialToolbar queueToolbar) {
    this.rootView = rootView;
    this.queueRecycler = queueRecycler;
    this.queueToolbar = queueToolbar;
  }

  @Override
  @NonNull
  public EdgeCoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentQueueBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentQueueBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_queue, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentQueueBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.queue_recycler;
      EdgeRecyclerView queueRecycler = ViewBindings.findChildViewById(rootView, id);
      if (queueRecycler == null) {
        break missingId;
      }

      id = R.id.queue_toolbar;
      MaterialToolbar queueToolbar = ViewBindings.findChildViewById(rootView, id);
      if (queueToolbar == null) {
        break missingId;
      }

      return new FragmentQueueBinding((EdgeCoordinatorLayout) rootView, queueRecycler,
          queueToolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
