// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager2.widget.ViewPager2;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.progressindicator.LinearProgressIndicator;
import com.google.android.material.tabs.TabLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.ui.coordinator.EdgeAppBarLayout;
import org.oxycblt.auxio.ui.coordinator.EdgeCoordinatorLayout;

public final class FragmentHomeBinding implements ViewBinding {
  @NonNull
  private final EdgeCoordinatorLayout rootView;

  @NonNull
  public final EdgeAppBarLayout homeAppbar;

  @NonNull
  public final FrameLayout homeContent;

  @NonNull
  public final FloatingActionButton homeFab;

  @NonNull
  public final Button homeIndexingAction;

  @NonNull
  public final ConstraintLayout homeIndexingContainer;

  @NonNull
  public final LinearProgressIndicator homeIndexingProgress;

  @NonNull
  public final TextView homeIndexingStatus;

  @NonNull
  public final EdgeCoordinatorLayout homeLayout;

  @NonNull
  public final ViewPager2 homePager;

  @NonNull
  public final TabLayout homeTabs;

  @NonNull
  public final MaterialToolbar homeToolbar;

  private FragmentHomeBinding(@NonNull EdgeCoordinatorLayout rootView,
      @NonNull EdgeAppBarLayout homeAppbar, @NonNull FrameLayout homeContent,
      @NonNull FloatingActionButton homeFab, @NonNull Button homeIndexingAction,
      @NonNull ConstraintLayout homeIndexingContainer,
      @NonNull LinearProgressIndicator homeIndexingProgress, @NonNull TextView homeIndexingStatus,
      @NonNull EdgeCoordinatorLayout homeLayout, @NonNull ViewPager2 homePager,
      @NonNull TabLayout homeTabs, @NonNull MaterialToolbar homeToolbar) {
    this.rootView = rootView;
    this.homeAppbar = homeAppbar;
    this.homeContent = homeContent;
    this.homeFab = homeFab;
    this.homeIndexingAction = homeIndexingAction;
    this.homeIndexingContainer = homeIndexingContainer;
    this.homeIndexingProgress = homeIndexingProgress;
    this.homeIndexingStatus = homeIndexingStatus;
    this.homeLayout = homeLayout;
    this.homePager = homePager;
    this.homeTabs = homeTabs;
    this.homeToolbar = homeToolbar;
  }

  @Override
  @NonNull
  public EdgeCoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.home_appbar;
      EdgeAppBarLayout homeAppbar = ViewBindings.findChildViewById(rootView, id);
      if (homeAppbar == null) {
        break missingId;
      }

      id = R.id.home_content;
      FrameLayout homeContent = ViewBindings.findChildViewById(rootView, id);
      if (homeContent == null) {
        break missingId;
      }

      id = R.id.home_fab;
      FloatingActionButton homeFab = ViewBindings.findChildViewById(rootView, id);
      if (homeFab == null) {
        break missingId;
      }

      id = R.id.home_indexing_action;
      Button homeIndexingAction = ViewBindings.findChildViewById(rootView, id);
      if (homeIndexingAction == null) {
        break missingId;
      }

      id = R.id.home_indexing_container;
      ConstraintLayout homeIndexingContainer = ViewBindings.findChildViewById(rootView, id);
      if (homeIndexingContainer == null) {
        break missingId;
      }

      id = R.id.home_indexing_progress;
      LinearProgressIndicator homeIndexingProgress = ViewBindings.findChildViewById(rootView, id);
      if (homeIndexingProgress == null) {
        break missingId;
      }

      id = R.id.home_indexing_status;
      TextView homeIndexingStatus = ViewBindings.findChildViewById(rootView, id);
      if (homeIndexingStatus == null) {
        break missingId;
      }

      EdgeCoordinatorLayout homeLayout = (EdgeCoordinatorLayout) rootView;

      id = R.id.home_pager;
      ViewPager2 homePager = ViewBindings.findChildViewById(rootView, id);
      if (homePager == null) {
        break missingId;
      }

      id = R.id.home_tabs;
      TabLayout homeTabs = ViewBindings.findChildViewById(rootView, id);
      if (homeTabs == null) {
        break missingId;
      }

      id = R.id.home_toolbar;
      MaterialToolbar homeToolbar = ViewBindings.findChildViewById(rootView, id);
      if (homeToolbar == null) {
        break missingId;
      }

      return new FragmentHomeBinding((EdgeCoordinatorLayout) rootView, homeAppbar, homeContent,
          homeFab, homeIndexingAction, homeIndexingContainer, homeIndexingProgress,
          homeIndexingStatus, homeLayout, homePager, homeTabs, homeToolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
