// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.FragmentContainerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.ui.BottomSheetLayout;

public final class FragmentMainBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final BottomSheetLayout bottomSheetLayout;

  @NonNull
  public final FragmentContainerView exploreNavHost;

  @NonNull
  public final FrameLayout layoutTooSmall;

  @NonNull
  public final FragmentContainerView playbackBarFragment;

  @NonNull
  public final FragmentContainerView playbackPanelFragment;

  private FragmentMainBinding(@NonNull FrameLayout rootView,
      @NonNull BottomSheetLayout bottomSheetLayout, @NonNull FragmentContainerView exploreNavHost,
      @NonNull FrameLayout layoutTooSmall, @NonNull FragmentContainerView playbackBarFragment,
      @NonNull FragmentContainerView playbackPanelFragment) {
    this.rootView = rootView;
    this.bottomSheetLayout = bottomSheetLayout;
    this.exploreNavHost = exploreNavHost;
    this.layoutTooSmall = layoutTooSmall;
    this.playbackBarFragment = playbackBarFragment;
    this.playbackPanelFragment = playbackPanelFragment;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bottom_sheet_layout;
      BottomSheetLayout bottomSheetLayout = ViewBindings.findChildViewById(rootView, id);
      if (bottomSheetLayout == null) {
        break missingId;
      }

      id = R.id.explore_nav_host;
      FragmentContainerView exploreNavHost = ViewBindings.findChildViewById(rootView, id);
      if (exploreNavHost == null) {
        break missingId;
      }

      id = R.id.layout_too_small;
      FrameLayout layoutTooSmall = ViewBindings.findChildViewById(rootView, id);
      if (layoutTooSmall == null) {
        break missingId;
      }

      id = R.id.playback_bar_fragment;
      FragmentContainerView playbackBarFragment = ViewBindings.findChildViewById(rootView, id);
      if (playbackBarFragment == null) {
        break missingId;
      }

      id = R.id.playback_panel_fragment;
      FragmentContainerView playbackPanelFragment = ViewBindings.findChildViewById(rootView, id);
      if (playbackPanelFragment == null) {
        break missingId;
      }

      return new FragmentMainBinding((FrameLayout) rootView, bottomSheetLayout, exploreNavHost,
          layoutTooSmall, playbackBarFragment, playbackPanelFragment);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
