// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.image.StyledImageView;

public final class ItemQueueSongBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final View background;

  @NonNull
  public final ConstraintLayout body;

  @NonNull
  public final StyledImageView songAlbumCover;

  @NonNull
  public final Button songDragHandle;

  @NonNull
  public final TextView songInfo;

  @NonNull
  public final TextView songName;

  private ItemQueueSongBinding(@NonNull FrameLayout rootView, @NonNull View background,
      @NonNull ConstraintLayout body, @NonNull StyledImageView songAlbumCover,
      @NonNull Button songDragHandle, @NonNull TextView songInfo, @NonNull TextView songName) {
    this.rootView = rootView;
    this.background = background;
    this.body = body;
    this.songAlbumCover = songAlbumCover;
    this.songDragHandle = songDragHandle;
    this.songInfo = songInfo;
    this.songName = songName;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemQueueSongBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemQueueSongBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_queue_song, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemQueueSongBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background;
      View background = ViewBindings.findChildViewById(rootView, id);
      if (background == null) {
        break missingId;
      }

      id = R.id.body;
      ConstraintLayout body = ViewBindings.findChildViewById(rootView, id);
      if (body == null) {
        break missingId;
      }

      id = R.id.song_album_cover;
      StyledImageView songAlbumCover = ViewBindings.findChildViewById(rootView, id);
      if (songAlbumCover == null) {
        break missingId;
      }

      id = R.id.song_drag_handle;
      Button songDragHandle = ViewBindings.findChildViewById(rootView, id);
      if (songDragHandle == null) {
        break missingId;
      }

      id = R.id.song_info;
      TextView songInfo = ViewBindings.findChildViewById(rootView, id);
      if (songInfo == null) {
        break missingId;
      }

      id = R.id.song_name;
      TextView songName = ViewBindings.findChildViewById(rootView, id);
      if (songName == null) {
        break missingId;
      }

      return new ItemQueueSongBinding((FrameLayout) rootView, background, body, songAlbumCover,
          songDragHandle, songInfo, songName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
