// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.checkbox.MaterialCheckBox;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;

public final class ItemTabBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button tabDragHandle;

  @NonNull
  public final MaterialCheckBox tabIcon;

  private ItemTabBinding(@NonNull ConstraintLayout rootView, @NonNull Button tabDragHandle,
      @NonNull MaterialCheckBox tabIcon) {
    this.rootView = rootView;
    this.tabDragHandle = tabDragHandle;
    this.tabIcon = tabIcon;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemTabBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemTabBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_tab, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemTabBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.tab_drag_handle;
      Button tabDragHandle = ViewBindings.findChildViewById(rootView, id);
      if (tabDragHandle == null) {
        break missingId;
      }

      id = R.id.tab_icon;
      MaterialCheckBox tabIcon = ViewBindings.findChildViewById(rootView, id);
      if (tabIcon == null) {
        break missingId;
      }

      return new ItemTabBinding((ConstraintLayout) rootView, tabDragHandle, tabIcon);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
