// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.image.StyledImageView;

public final class ItemDiscHeaderBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final StyledImageView discItem;

  @NonNull
  public final TextView discNo;

  private ItemDiscHeaderBinding(@NonNull ConstraintLayout rootView,
      @NonNull StyledImageView discItem, @NonNull TextView discNo) {
    this.rootView = rootView;
    this.discItem = discItem;
    this.discNo = discNo;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemDiscHeaderBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemDiscHeaderBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_disc_header, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemDiscHeaderBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.disc_item;
      StyledImageView discItem = ViewBindings.findChildViewById(rootView, id);
      if (discItem == null) {
        break missingId;
      }

      id = R.id.disc_no;
      TextView discNo = ViewBindings.findChildViewById(rootView, id);
      if (discNo == null) {
        break missingId;
      }

      return new ItemDiscHeaderBinding((ConstraintLayout) rootView, discItem, discNo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
