// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;
import org.oxycblt.auxio.image.ImageGroup;

public final class ItemParentBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageGroup parentImage;

  @NonNull
  public final TextView parentInfo;

  @NonNull
  public final TextView parentName;

  private ItemParentBinding(@NonNull ConstraintLayout rootView, @NonNull ImageGroup parentImage,
      @NonNull TextView parentInfo, @NonNull TextView parentName) {
    this.rootView = rootView;
    this.parentImage = parentImage;
    this.parentInfo = parentInfo;
    this.parentName = parentName;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemParentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemParentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_parent, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemParentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.parent_image;
      ImageGroup parentImage = ViewBindings.findChildViewById(rootView, id);
      if (parentImage == null) {
        break missingId;
      }

      id = R.id.parent_info;
      TextView parentInfo = ViewBindings.findChildViewById(rootView, id);
      if (parentInfo == null) {
        break missingId;
      }

      id = R.id.parent_name;
      TextView parentName = ViewBindings.findChildViewById(rootView, id);
      if (parentName == null) {
        break missingId;
      }

      return new ItemParentBinding((ConstraintLayout) rootView, parentImage, parentInfo,
          parentName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
