// Generated by view binder compiler. Do not edit!
package org.oxycblt.auxio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.oxycblt.auxio.R;

public final class WidgetWideBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final RelativeLayout background;

  @NonNull
  public final ImageView widgetAspectRatio;

  @NonNull
  public final LinearLayout widgetControls;

  @NonNull
  public final ImageView widgetCover;

  @NonNull
  public final ImageButton widgetPlayPause;

  @NonNull
  public final ImageButton widgetRepeat;

  @NonNull
  public final ImageButton widgetShuffle;

  @NonNull
  public final ImageButton widgetSkipNext;

  @NonNull
  public final ImageButton widgetSkipPrev;

  private WidgetWideBinding(@NonNull RelativeLayout rootView, @NonNull RelativeLayout background,
      @NonNull ImageView widgetAspectRatio, @NonNull LinearLayout widgetControls,
      @NonNull ImageView widgetCover, @NonNull ImageButton widgetPlayPause,
      @NonNull ImageButton widgetRepeat, @NonNull ImageButton widgetShuffle,
      @NonNull ImageButton widgetSkipNext, @NonNull ImageButton widgetSkipPrev) {
    this.rootView = rootView;
    this.background = background;
    this.widgetAspectRatio = widgetAspectRatio;
    this.widgetControls = widgetControls;
    this.widgetCover = widgetCover;
    this.widgetPlayPause = widgetPlayPause;
    this.widgetRepeat = widgetRepeat;
    this.widgetShuffle = widgetShuffle;
    this.widgetSkipNext = widgetSkipNext;
    this.widgetSkipPrev = widgetSkipPrev;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static WidgetWideBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static WidgetWideBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.widget_wide, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static WidgetWideBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      RelativeLayout background = (RelativeLayout) rootView;

      id = R.id.widget_aspect_ratio;
      ImageView widgetAspectRatio = ViewBindings.findChildViewById(rootView, id);
      if (widgetAspectRatio == null) {
        break missingId;
      }

      id = R.id.widget_controls;
      LinearLayout widgetControls = ViewBindings.findChildViewById(rootView, id);
      if (widgetControls == null) {
        break missingId;
      }

      id = R.id.widget_cover;
      ImageView widgetCover = ViewBindings.findChildViewById(rootView, id);
      if (widgetCover == null) {
        break missingId;
      }

      id = R.id.widget_play_pause;
      ImageButton widgetPlayPause = ViewBindings.findChildViewById(rootView, id);
      if (widgetPlayPause == null) {
        break missingId;
      }

      id = R.id.widget_repeat;
      ImageButton widgetRepeat = ViewBindings.findChildViewById(rootView, id);
      if (widgetRepeat == null) {
        break missingId;
      }

      id = R.id.widget_shuffle;
      ImageButton widgetShuffle = ViewBindings.findChildViewById(rootView, id);
      if (widgetShuffle == null) {
        break missingId;
      }

      id = R.id.widget_skip_next;
      ImageButton widgetSkipNext = ViewBindings.findChildViewById(rootView, id);
      if (widgetSkipNext == null) {
        break missingId;
      }

      id = R.id.widget_skip_prev;
      ImageButton widgetSkipPrev = ViewBindings.findChildViewById(rootView, id);
      if (widgetSkipPrev == null) {
        break missingId;
      }

      return new WidgetWideBinding((RelativeLayout) rootView, background, widgetAspectRatio,
          widgetControls, widgetCover, widgetPlayPause, widgetRepeat, widgetShuffle, widgetSkipNext,
          widgetSkipPrev);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
